@startuml

actor "Gestor de Organizacao"
activate "Gestor de Organizacao"
"Gestor de Organizacao" -> ":Sistema" : 1 Inicia o processo de adjudicacao de uma tarefa
activate ":Sistema"
":Sistema" --> "Gestor de Organizacao" : 2 pergunta qual o anuncio ja seriado que pretende escolher
deactivate ":Sistema"
"Gestor de Organizacao" -> ":Sistema" : 3 seleciona um anuncio seriado
activate ":Sistema"
":Sistema" --> "Gestor de Organizacao" : 4 mostra a classificacao do anuncio ja seriado e solicita a data de inicio
deactivate ":Sistema" 
"Gestor de Organizacao" -> ":Sistema" : 5 introduz os dados solicitados e confirma operacao
activate ":Sistema"
":Sistema" --> "Gestor de Organizacao" : 8 adjudica a tarefa e informa do sucesso da operacao
deactivate ":Sistema"

@enduml