@startuml

left to right direction

title UC5 - Especificar Colaboradores da Organização\n

Class Plataforma <<Singleton>> {
designacao
--
validaLogin()
validaColaborador()
adicionaColaborador()
}

Class Colaborador{
String: nome
String: funcao
String: contactoTelefonico
String: email
String: password
--
isGestor()==true
}

Class UC5_UI{
novoLogin()
novoColaborador()
registaColaborador()
}

Class UC5_CTRL{
login=novoLogin()
colaborador=novoColaborador()
criar()
registaColaborador()
}

Plataforma --o Colaborador
Colaborador --> UC5_UI
UC5_UI --> UC5_CTRL

@enduml