@startuml



gestor -> UC5_CTRL: lerDados(nome,email,telefone,gestor)

UC5_CTRL -> UC5_CTRL: registarOrganizacao(nome,email,telefone,gestor)
UC5_CTRL -> "repo:RepositorioOrganizacao": create
UC5_CTRL <-- "repo:RepositorioOrganizacao": repo

UC5_CTRL -> "repo:RepositorioOrganizacao": organizacao
UC5_CTRL <-- "repo:RepositorioOrganizacao": org

"repo:RepositorioOrganizacao" -> "org:Organizacao": find
"repo:RepositorioOrganizacao" <-- "org:Organizacao": find

UC5_CTRL -> "repoCol:RepositorioColaborador": create
UC5_CTRL <-- "repoCol:RepositorioOrganizacao": repoCol

UC5_CTRL -> "c:Colaborador": create(nome,email,telefone,gestor)
UC5_CTRL -> "c:Colaborador": c

UC5_CTRL --> 
Uc5_UI --> UC5_CTRL: 

@enduml