@startuml

title UC12 - Candidatura a Freelancer

participant CandidatoFreelancer
participant UC12_UI
participant UC12_Ctrl
participant UC12_Builder
participant Plataforma << Singleton >>

CandidatoFreelancer -> UC12_UI: preencher candidatura
activate CandidatoFreelancer
activate UC12_UI
CandidatoFreelancer -> UC12_UI: preencher dados pessoais \n(nome, enderecoPostal, contactoTelefonico, email)
UC12_UI -> UC12_Ctrl: preencherDadosPessoais \n(nome, enderecoPostal, contactoTelefonico, email)
activate UC12_Ctrl
UC12_Ctrl -> UC12_Builder: preencherDadosPessoais \n(nome, enderecoPostal, contactoTelefonico, email)
activate UC12_Builder
UC12_Builder --> UC12_Ctrl: success
deactivate UC12_Builder
UC12_Ctrl --> UC12_UI: success
deactivate UC12_Ctrl
UC12_UI --> CandidatoFreelancer: success
deactivate UC12_UI

CandidatoFreelancer -> UC12_UI: preencher Habilitacoes Literarias \n(grauEnsino, instituicaoEnsino, curso, mediaCurso)
activate UC12_UI
CandidatoFreelancer -> UC12_UI: preencher Habilitações Literárias \n(grauEnsino, instituicaoEnsino, curso, mediaCurso)
UC12_UI -> UC12_Ctrl: preencherHabilitacoesLiterarias \n(grauEnsino, instituicaoEnsino, curso, mediaCurso)
activate UC12_Ctrl
UC12_Ctrl -> UC12_Builder: preencherHabilitacoesLiterarias \n(grauEnsino, instituicaoEnsino, curso, mediaCurso)
activate UC12_Builder
UC12_Builder --> UC12_Ctrl: success
deactivate UC12_Builder
UC12_Ctrl --> UC12_UI: success
deactivate UC12_Ctrl
UC12_UI --> CandidatoFreelancer: success
deactivate UC12_UI
deactivate Plataforma

activate UC12_Ctrl
UC12_Ctrl -> UC12_Builder: createCandidatoFreelancer \n(dadosPessoais, habilitacoesLiterarias)
deactivate UC12_Ctrl
activate UC12_Builder
UC12_Builder -> UC12_Builder: new CandidatoFreelancer\n(dadosPessoais, habilitacoesLiterarias)


UC12_Builder -> Plataforma: addCandidatoFreelancer(candidatoFreelancer)
deactivate UC12_Builder
activate Plataforma

Plataforma -->UC12_Ctrl: returns (candidatoFreelancer)
deactivate Plataforma
activate UC12_Ctrl
UC12_Ctrl --> UC12_UI: returns (candidatoFreelancer)
deactivate UC12_Ctrl
activate UC12_UI
UC12_UI --> CandidatoFreelancer: candidatura bem sucedida
deactivate UC12_UI
deactivate CandidatoFreelancer


@enduml