@startuml 
actor Administrativo as Administrativo
Administrativo -> "AreaAdministrativoUI" : 1 Introduz os dados solicitados
activate Administrativo
activate "AreaAdministrativoUI"
"AreaAdministrativoUI" -> "RegistrarFreelancerController" : 2 registarFreelancer(nomeFreelancer, contactoFreelancer,\n emailFreelancer, nifFreelancer, reconhecimento, habilitacoes)
activate "RegistrarFreelancerController"
"RegistrarFreelancerController" -> "rf:RepositorioFreelancer" : 6 freelancer = criarFreelancer(nomeFreelancer,\n contactoFreelancer, emailFreelancer,\n nifFreelancer, reconhecimento, habilitacoes)
activate "rf:RepositorioFreelancer"
"rf:RepositorioFreelancer" -> NIF ** : 7 create(nif)
"rf:RepositorioFreelancer" -> Telefone ** : 9 create(contacto)
"rf:RepositorioFreelancer" -> Email ** : 10 create(email)
group loop
"rf:RepositorioFreelancer" -> HabilitacaoAcademica ** : 11 create(grau, designacaoCurso, nomeInstituicao, mediaCurso)
end
group loop
    "rf:RepositorioFreelancer" -> ReconhecimentoCT ** : 11 create(competenciaTecnica, grauProficiencia, dataReconhecimento)
end
"rf:RepositorioFreelancer" -> Freelancer ** : 12 create(nomeFreelancer, contactoFreelancer, emailFreelancer, nifFreelancer, reconhecimento, habilitacoes)
deactivate "rf:RepositorioFreelancer"
"RegistrarFreelancerController" -> "rf:RepositorioFreelancer" : 17 addFreelancer(freelancer)
activate "rf:RepositorioFreelancer"
"RegistrarFreelancerController" <-- "rf:RepositorioFreelancer" : 18 ok
deactivate "rf:RepositorioFreelancer"
deactivate "RegistrarFreelancerController"
"AreaAdministrativoUI" --> Administrativo : 23 operação bem sucedida, \n mostra dados
deactivate "AreaAdministrativoUI"
@enduml