@startuml 

user -> UC1_UI:lerDados(nome) 
UC1_UI -> UC1_CTRL:registarOrganizacao(nome)
UC1_CTRL -> "org:Organizacao": create
UC1_CTRL <-- "org:Organizacao": org

'UC1_CTRL -> "repo:RepositorioOrganizacao": create
'UC1_CTRL <-- "repo:RepositorioOrganizacao": repo

UC1_CTRL -> FabricaRepositorios:reposicaoOrganizacao()

FabricaRepositorios -> "repo:RepositorioOrganizacao": create
FabricaRepositorios <-- "repo:RepositorioOrganizacao": repo

UC1_CTRL <-- FabricaRepositorios:repo


UC1_CTRL -> "repo:RepositorioOrganizacao": adicionar(org)

UC1_CTRL --> UC1_UI: org

UC1_UI --> UC1_UI: show(org)
@enduml