@startuml

title UC8 - Diagrama de sequência

actor ColaboradorUtilizador
participant AreaColaboradorUI
participant PublicarTarefaCTRL



activate ColaboradorUtilizador
ColaboradorUtilizador -> AreaColaboradorUI: 1 Inicia a publicação de uma tarefa
activate AreaColaboradorUI

AreaColaboradorUI -> PublicarTarefaCTRL: 4 publicarTarefa(Tarefa tarefa,\n TipoRegimento tipoRegimento,\n Data dataInicioPublicitacao,\n LocalDate dataFimPublicitacao,\n LocalDate dataInicioCandidatura,\n LocalDate dataFimCandidatura,\n LocalDate dataInicioSeriacao,\n LocalDate dataFimSeriacao)
activate PublicarTarefaCTRL
PublicarTarefaCTRL -> "rt:RepositorioTarefa" : 5 repoTarefa = RepositorioTarefa.getInstance()
activate "rt:RepositorioTarefa"
deactivate "rt:RepositorioTarefa"



PublicarTarefaCTRL -> "ra:RepositorioAnuncio" : 13 plat.getRepoAnuncio()
activate "ra:RepositorioAnuncio"
deactivate "ra:RepositorioAnuncio"
PublicarTarefaCTRL -> "ra:RepositorioAnuncio" : 14 anuncio = publicarTarefa()
activate "ra:RepositorioAnuncio"
"ra:RepositorioAnuncio" -> CodigoUnico** : 15 create(codigoUnico)
PublicarTarefaCTRL -> "ra:RepositorioAnuncio" : 16 addAnuncio(anuncio)
"ra:RepositorioAnuncio" --> PublicarTarefaCTRL : 17 ok
deactivate "ra:RepositorioAnuncio"
deactivate PublicarTarefaCTRL
AreaColaboradorUI --> ColaboradorUtilizador : 18 operação bem sucedida
deactivate AreaColaboradorUI
deactivate ColaboradorUtilizador


@enduml