@startuml

left to right direction

title UC3 - Definir Categoria de Tarefa \n

Class Plataforma <<Singleton>> {
    -String designacao

    +getRegistoAreasAtividade()
    +getRegistoCompetenciasTecnicas()
    +getRegistoCategorias()
}


Class CompetenciaTecnica {
    -String codigo
    -String descricaoBreve
    -String descricaoDetalhada

    +getGrausProficiencia(CompetenciaTecnica competenciaTecnica)
    +getGrauProficiencia(GrauProficiencia grauProficiencia)
}

Class UC3_UI {
}

Class UC3_CTRL {
    +getListaAreasAtividade()
    +novaAreaAtividade(String descricao, int codAreaAtividade)
    +getGrausProficiencia(CompetenciaTecnica competenciaTecnica)
    +setProficienciaObrigatoriedade(codGrau, obrigatoria)
    +registarCategoria()
}

Class Categoria {
    -String id
    -String descricao

    +create(String idCategoria, String descricao, AreaAtividade areaAtividade)
    +novaCaracterizacao(CompetenciaTecnica compTec, GrauProficiencia grauProf, boolean obrigatoria)
    +addCaracterizacaoCT(CaracterizacaoCT)
}

Class CaracterizacaoCT {
    -boolean caracter

    +create(CompetenciaTecnica compTec, GrauProficiencia grauProf, boolean obrigatoria)
}


Class RegistoAreasAtividade {
    +getListaAreasAtividade()
    +getAreaAtividade(int codAreaAtividade)
}

Class RegistoCompetenciasTecnicas {
    +getListaCompetenciasTecnicas(AreaAtividade areaAtividade)
    +getCompetenciaTecnica(int codCompetencia)
}

Class RegistoCategorias {
    +novaCategoria(String descricao, Area Atividade areaAtividade)
    +getIdCategoria()
    +registaCategoria(Categoria categoria)
    +valida(Categoria categoria)
    +addCategoria(Categoria categoria)
}

UC3_UI .> UC3_CTRL

UC3_CTRL .> Plataforma
UC3_CTRL .> RegistoAreasAtividade
UC3_CTRL .> RegistoCompetenciasTecnicas
UC3_CTRL .> RegistoCategorias
UC3_CTRL .> CompetenciaTecnica
UC3_CTRL .> Categoria

Plataforma "1" -down-> "1" RegistoAreasAtividade: tem
Plataforma "1" -down-> "1" RegistoCompetenciasTecnicas: tem
Plataforma "1" -down-> "1" RegistoCategorias: tem

RegistoCategorias "1" -> "*" Categoria: possui
RegistoCategorias .> Categoria
RegistoAreasAtividade "1" -> "*" AreaAtividade: possui
RegistoCompetenciasTecnicas "1" -> "*" CompetenciaTecnica: possui

Categoria "1" -> "*" CaracterizacaoCT: possui

@enduml