@startuml

left to right direction

Class Plataforma <<Singleton>> {
designacao
--
validaTarefa()
addTarefa()
}

Class Colaborador{
String: nome
String: funcao
String: contactoTelefonico
String: email
String: password
}

Class UC6_UI{
novaTarefa()
registarTarefa()
}

Class UC6_CTRL{
tarefa=novaTarefa()
criar()
registarTarefa()
}
Class Tarefa{
    -designacao
    -descricaoInformal
    -descricaoTecnica
    -prazo
    -custo
    -categTarefa
}
Plataforma --o Colaborador
Colaborador --> UC6_UI
UC6_UI --> UC6_CTRL
UC6_CTRL --> Tarefa

@enduml