@startuml

'sem fabrica

user -> UC1_UI: lerDados(nome)
UC1_UI -> UC1_CTRL: registarOrganizacao(nome)
UC1_CTRL -> Organizacao: create
UC1_CTRL <-- Organizacao: org
'UC1_CTRL -> RepositorioOrganizacao : create(org)
'UC1_CTRL <-- RepositorioOrganizacao : repo(org)
UC1_CTRL -> RepositorioOrganizacao : add(org)

UC1_CTRL -> FabricaRepositorios: repositorioOrganizacao()
FabricaRepositorios -> "repo:RepositorioOrganizacao": create
FabricaRepositorios <-- "repo:RepositorioOrganizacao": repo

UC1_CTRL <-- FabricaRepositorios: repo
UC1_CTRL --> UC1_UI: org (devia devolver dto)
UC1_UI --> UC1_UI: show(org)



@enduml