@startuml
interface AlgoritmoGeradorPasswords <<interface>>{
    +String geraPassword(String nome, String email)
}
note left: Esta interface será alvo \nde multiplas implementações,\numa por cada algoritmo externo\nque tenha que ser suportado.
class AlgoritmoGeradorPasswordsAdapter1{
    +String geraPassword(String nome, String email)
}
class AlgoritmoGeradorPasswordsAdapter2{
 +String geraPassword(String nome, String email)
}
class AlgoritmoExterno1API{
    +String randomPassword()
    +String randomPassword(Integer minChars, Integer maxChars)
}
class AlgoritmoExterno2API{
    +Password generatedPassword()
    +Password generaterPassword(String feedChars)
    +Password generatedPassword(Integer strength)
    +Password generatedPassword(Integer strenght, String feedChars)
}
AlgoritmoGeradorPasswords <|.. AlgoritmoGeradorPasswordsAdapter1
AlgoritmoGeradorPasswords <|.. AlgoritmoGeradorPasswordsAdapter2
AlgoritmoGeradorPasswordsAdapter1 --> AlgoritmoExterno1API
AlgoritmoGeradorPasswordsAdapter2 --> AlgoritmoExterno2API
@enduml